# -*- coding: utf-8 -*-
"""kNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jFoMkOKhhPejFwRM5QHWueb3AB3quSqs
"""

from sklearn.base import BaseEstimator,ClassifierMixin
from scipy.spatial import distance
from scipy.stats import mode

class kNN(BaseEstimator, ClassifierMixin):
  def __init__(self, n_neighbors:int = 5):
    self.n_neighbors = n_neighbors
  
  def fit(self, X, y):
    self.X = np.copy(X)
    self.y = np.copy(y)
    return self
 
  def predict(self, X):
    dists = distance.cdist(self.X, X, 'euclidean')
    idxs = np.argpartition(dists, self.n_neighbors, axis=0)[:self.n_neighbors]
    nearest = np.take(self.y, idxs)
    predictions = mode(nearest, axis=0)[0]
    return predictions[0]